### PR TITLE
Added basic minimal BTK build instructions needed for Linux

### PR DESCRIPTION
**Pull request by andreyzhd**

### CODE REVIEW

**Comment by jjnurminen** [comment]
I'm wondering if the stanza in gui/_gaitmenu.py is necessary, since gui/gaitmenu.py was designed to be run?

**Comment by andreyzhd** [comment]
Good point. However, the reason that I've missed it is that I've checked the setup.py and that one specifies gaitutils.gui._gaitmenu:main as the entry point. Is there a reason that setup.py doesn't specify gui/gaitmenu.py?

**Comment by jjnurminen** [comment]
I don't remember the reason. Is it so that the entry points need to be functions? And then the gaitmenu.py script was needed for something else, maybe the shortcut mechanism.

**Comment by jjnurminen** [comment]
But feel free to refactor as you wish - maybe gaitmenu.py can be deleted.

**Pull request merged**
